# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'App' do
  use_frameworks!

  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'   # Push notifications
  pod 'Firebase/Storage'

  target 'AppTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
